apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jaeger-app-of-apps
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/ashutosh-18k92/gitops-v2.git
    targetRevision: HEAD
    path: jaeger
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

