# infrastructure/cluster-level/istio-control-plane/istio-operator-cr.yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istio-control-plane
  namespace: istio-system
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  profile: default
  hub: docker.io/istio
  tag: 1.28.0
  
  meshConfig:
    accessLogFile: /dev/stdout
    enableTracing: true
    defaultConfig:
      tracing:
        sampling: 100.0  # 100% for dev, reduce for prod
        zipkin:
          address: jaeger-collector.observability.svc.cluster.local:9411
    
    extensionProviders:
      - name: jaeger
        zipkin:
          service: jaeger-collector.observability.svc.cluster.local
          port: 9411
  
  components:
    pilot:
      enabled: true
      k8s:
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
    
    ingressGateways:
      - name: istio-ingressgateway
        enabled: true
        k8s:
          service:
            type: LoadBalancer
    
    egressGateways:
      - name: istio-egressgateway
        enabled: false