apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: jaeger-tracing
  namespace: observability
  annotations:
    argocd.argoproj.io/sync-wave: "20"
  
spec:
  strategy: production
  collector:
    replicas: 1
    resources:
      requests:
        cpu: 128m
        memory: 128Mi
        
  query:
    replicas: 1

  ingester:
    replicas: 1

  storage:
    type: elasticsearch
    elasticsearch:
      nodeCount: 1
      redundancyPolicy: "SingleRedundancy"
      esIndexCleaner:
        enabled: true
        numberOfDays: 1

