---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: dockerhub-secret
  namespace: default
spec:
  encryptedData:
    .dockerconfigjson: AgBhu/ciE0SVNZdIbHifUAx5LiO55k3z/sPJUJERViWghmnrkBGiZp0ZzwJuoubRP2U4dzqTkQeRCbhtHjkSMnAwUNeihgZCoE6DWaK+hRl/CpDlQHn2NbWKtkQFVmEEwgXQxI9yZqAFSfNaLFbhb1xS9bEcXrhTIOCpCp88LIzLgY1SFnYir8h6dt8CWVODo7zJ5cwhX4BGSOm3+5hpOYaY5RrOQELASRDp5HFLGJBeBKpZ9YFlAeAyHn6YE7g7Z5lxGm1dW8MAxyxPOJC+oEnGN6qYx6reA2oNoJDqE62PCRZo5mRyPzPOGfbpwW5rDmhH9Q2cUf2lWWRDmoSLITwiA+yoUmHdygKIYg4cMQKQzWBTvprBkNsuNy00R43xPaAYhGhqQirlgfUyjt09pQee2oF7WXAL9+aKrz8XlN+aX9YVhrpEcMuollTi2wQ27A//oni6gw684qJblLOjkUao+JL7abo12dzU+WL41jsV7j1oIv1tUG28xpjyZJGUg95bJpf5yyHQJcLUuXq8zI1remu6yBATSEj1V0HKiVCzJut7kaa7GzcgoWH/IMiawyrmlMij4BzXsretYVhokgUsU5GUJjsKp9zIjxjWovBxVLjMgY3qmEkXWDAuZvA2AupJUtxdvhEiLn0u4IkgN35ZhHaGEkjErm6HACsip8J4ubujjluF5eOmzQ8k40ogdMN87cyWaiXxRBg/MXSiZQRKpTFTmzJ/mXDFyD0CEk2832ljyIZrLnT1MwPcC1ivugpisdGCb+hDnaqwJeayo2Hzj5+51M09/3syKd4Ld3aw8B6M58PV+y0nDDWOvXweuchjSA5wRpHY/Mq7tXMgaU5fg+Ey6EwHoHH8UYI60oLATuZJaYMNNS1K+Gp455ilr7Z9zT7V+MP6997QduzFXaJC5BX8yoSvoKlicrXoyLMKVhP97xT2PhRy2DXF4Gzr/dlvxIKB3vXhtV1ZyqMdDTQggKTb/QLViBg5ESS42b9iXsy9CQ8IbGYpcJKC3EBnuQNu
  template:
    metadata:
      name: dockerhub-secret
      namespace: default
    type: kubernetes.io/dockerconfigjson
