# infrastructure/cluster-level/istio-operator/application.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://istio-release.storage.googleapis.com/charts
    chart: operator
    targetRevision: 1.28.0
    helm:
      valuesObject:
        hub: docker.io/istio
        tag: 1.28.0
        operatorNamespace: istio-operator
        watchedNamespaces: istio-system
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true