apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: aggregator-service
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - list:
        elements:
          - env: dev
            namespace: super-fortnight-dev
          # - env: staging
          # namespace: super-fortnight-staging
          # - env: production
          # namespace: super-fortnight
  template:
    metadata:
      name: "aggregator-service-{{.env}}"
      namespace: argocd
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: default
      sources:
        # Source 1: Helm chart from sf-helm-registry with values
        - repoURL: https://github.com/ashutosh-18k92/sf-helm-registry.git
          targetRevision: main
          path: api
          helm:
            releaseName: aggregator
            valueFiles:
              - $values/deploy/base/values.yaml
              - $values/deploy/overlays/{{.env}}/values.yaml

        # Source 2: Values from aggregator-service repo
        - repoURL: https://github.com/ashutosh-18k92/aggregator-service.git
          targetRevision: main
          ref: values
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{.namespace}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        # syncOptions:
        #   - CreateNamespace=true
      ignoreDifferences:
        - group: apps
          kind: Deployment
          jsonPointers:
            - /spec/replicas
