apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aggregator-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/ashutosh-18k92/gitops-v2.git
    targetRevision: HEAD
    path: services/aggregator
    kustomize:
      version: v5.0.0
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
